# Generated by Django 2.2.16 on 2022-04-07 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220407_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('6f3ae528-6567-42e6-a08d-aa450316c5d0'), verbose_name='UUID'),
        ),
    ]
