# Generated by Django 2.2.16 on 2022-04-07 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220407_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('9f16e774-cb11-425e-8642-07d35b8e5dee'), verbose_name='UUID'),
        ),
    ]
