# Generated by Django 2.2.16 on 2022-04-22 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220407_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('baebddfb-bcdc-4b55-a337-e11a85c416aa'), verbose_name='UUID'),
        ),
    ]
