# Generated by Django 2.2.16 on 2022-04-07 17:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('reviews', '0002_auto_20220407_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
